apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  replicas: 1 # tells deployment to run 1 pods matching the template
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
metadata:
  name: lb-wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  ports:
    - port: 5050
      name: http
      protocol: TCP
      targetPort: 5050
  selector:
    app: wordpress